content:
    path: '/{slug}'
    methods:  ['GET']
    defaults: { _controller: 'teknoo.east.website.endpoint.content', slug: '' }

media:
    path: '/media/{id}'
    methods:  ['GET']
    defaults: { _controller: 'teknoo.east.website.endpoint.media' }
