parameters:
  teknoo.east.website.endpoint.content.class: 'Teknoo\East\WebsiteBundle\EndPoint\ContentEndPoint'
  teknoo.east.website.endpoint.media.class: 'Teknoo\East\WebsiteBundle\EndPoint\MediaEntPoint'

services:
  teknoo.east.website.endpoint.content:
    class: '%teknoo.east.website.endpoint.content.class%'
    arguments:
      - '@Teknoo\East\Website\Loader\ContentLoader'
      - '@Teknoo\East\Website\Service\MenuGenerator'

  teknoo.east.website.endpoint.media:
    class: '%teknoo.east.website.endpoint.media.class%'
    arguments:
      - '@Teknoo\East\Website\Loader\MediaLoader'
