parameters:
  #Front endpoints
  teknoo.east.website.endpoint.content.class: 'Teknoo\East\WebsiteBundle\EndPoint\ContentEndPoint'
  teknoo.east.website.endpoint.media.class: 'Teknoo\East\WebsiteBundle\EndPoint\MediaEndPoint'
  teknoo.east.website.endpoint.static.class: 'Teknoo\East\WebsiteBundle\EndPoint\StaticEndPoint'

  #Admin endpoints
  teknoo.east.website.endpoint.admin.delete.class: 'Teknoo\East\WebsiteBundle\AdminEndPoint\AdminDeleteEndPoint'
  teknoo.east.website.endpoint.admin.edit.class: 'Teknoo\East\WebsiteBundle\AdminEndPoint\AdminEditEndPoint'
  teknoo.east.website.endpoint.admin.list.class: 'Teknoo\East\WebsiteBundle\AdminEndPoint\AdminListEndPoint'
  teknoo.east.website.endpoint.admin.new.class: 'Teknoo\East\WebsiteBundle\AdminEndPoint\AdminNewEndPoint'

  #Admin form types
  teknoo.east.website.form_type.category.class: 'Teknoo\East\WebsiteBundle\Form\Type\CategoryType'
  teknoo.east.website.form_type.content.class: 'Teknoo\East\WebsiteBundle\Form\Type\ContentType'
  teknoo.east.website.form_type.media.class: 'Teknoo\East\WebsiteBundle\Form\Type\MediaType'
  teknoo.east.website.form_type.type.class: 'Teknoo\East\WebsiteBundle\Form\Type\TypeType'
  teknoo.east.website.form_type.user.class: 'Teknoo\East\WebsiteBundle\Form\Type\UserType'

  #Class
  teknoo.east.website.category.class: 'Teknoo\East\Website\Object\Category'
  teknoo.east.website.content.class: 'Teknoo\East\Website\Object\Content'
  teknoo.east.website.media.class: 'Teknoo\East\Website\Object\Media'
  teknoo.east.website.type.class: 'Teknoo\East\Website\Object\Type'
  teknoo.east.website.user.class: 'Teknoo\East\Website\Object\User'

  #Admin view path
  teknoo.east.website.view.category.new.file: 'TeknooEastWebsiteBundle:AdminCategory:new.html.twig'
  teknoo.east.website.view.category.edit.file: 'TeknooEastWebsiteBundle:AdminCategory:edit.html.twig'
  teknoo.east.website.view.category.list.file: 'TeknooEastWebsiteBundle:AdminCategory:list.html.twig'

  teknoo.east.website.view.content.new.file: 'TeknooEastWebsiteBundle:AdminContent:new.html.twig'
  teknoo.east.website.view.content.edit.file: 'TeknooEastWebsiteBundle:AdminContent:edit.html.twig'
  teknoo.east.website.view.content.list.file: 'TeknooEastWebsiteBundle:AdminContent:list.html.twig'

  teknoo.east.website.view.media.new.file: 'TeknooEastWebsiteBundle:AdminMedia:new.html.twig'
  teknoo.east.website.view.media.list.file: 'TeknooEastWebsiteBundle:AdminMedia:list.html.twig'

  teknoo.east.website.view.type.new.file: 'TeknooEastWebsiteBundle:AdminType:new.html.twig'
  teknoo.east.website.view.type.edit.file: 'TeknooEastWebsiteBundle:AdminType:edit.html.twig'
  teknoo.east.website.view.type.list.file: 'TeknooEastWebsiteBundle:AdminType:list.html.twig'

  teknoo.east.website.view.user.new.file: 'TeknooEastWebsiteBundle:AdminUser:new.html.twig'
  teknoo.east.website.view.user.edit.file: 'TeknooEastWebsiteBundle:AdminUser:edit.html.twig'
  teknoo.east.website.view.user.list.file: 'TeknooEastWebsiteBundle:AdminUser:list.html.twig'

  #Provider
  teknoo.east.website.bundle.user_provider.class: 'Teknoo\East\WebsiteBundle\Provider\UserProvider'

  #Command
  teknoo.east.website.bundle.command.create_user.class: 'Teknoo\East\WebsiteBundle\Command\CreateUserCommand'

  #Writer
  teknoo.east.website.bundle.writer.user.class: 'Teknoo\East\WebsiteBundle\Writer\UserWriter'

services:
  #Front endpoints
  teknoo.east.website.endpoint.content:
    class: '%teknoo.east.website.endpoint.content.class%'
    arguments:
      - '@Teknoo\East\Website\Loader\ContentLoader'
    calls:
      - ['setTemplating', ['@templating.engine.twig']]

  teknoo.east.website.endpoint.media:
    class: '%teknoo.east.website.endpoint.media.class%'
    arguments:
      - '@Teknoo\East\Website\Loader\MediaLoader'
    calls:
      - ['setTemplating', ['@templating.engine.twig']]

  teknoo.east.website.endpoint.static:
    class: '%teknoo.east.website.endpoint.static.class%'
    calls:
      - ['setTemplating', ['@templating.engine.twig']]

  #Admin endpoints
  teknoo.east.website.endpoint.admin.delete.abstract:
    class: '%teknoo.east.website.endpoint.admin.delete.class%'

  teknoo.east.website.endpoint.admin.edit.abstract:
    class: '%teknoo.east.website.endpoint.admin.edit.class%'
    calls:
      - ['setFormFactory', ['@form.factory']]

  teknoo.east.website.endpoint.admin.list.abstract:
    class: '%teknoo.east.website.endpoint.admin.list.class%'

  teknoo.east.website.endpoint.admin.new.abstract:
    class: '%teknoo.east.website.endpoint.admin.new.class%'
    calls:
      - ['setFormFactory', ['@form.factory']]

  #Categories
  teknoo.east.website.endpoint.admin.delete.category:
    parent: 'teknoo.east.website.endpoint.admin.delete.abstract'
    calls:
      - ['setDeletingService', ['@teknoo.east.website.deleting.category']]
      - ['setLoader', ['@Teknoo\East\Website\Loader\CategoryLoader']]
      - ['setRouter', ['@router']]

  teknoo.east.website.endpoint.admin.edit.category:
    parent: 'teknoo.east.website.endpoint.admin.edit.abstract'
    calls:
      - ['setLoader', ['@Teknoo\East\Website\Loader\CategoryLoader']]
      - ['setWriter', ['@Teknoo\East\Website\Writer\CategoryWriter']]
      - ['setFormClass', ['%teknoo.east.website.form_type.category.class%']]
      - ['setViewPath', ['%teknoo.east.website.view.category.edit.file%']]
      - ['setTemplating', ['@templating.engine.twig']]

  teknoo.east.website.endpoint.admin.list.category:
    parent: 'teknoo.east.website.endpoint.admin.list.abstract'
    calls:
      - ['setLoader', ['@Teknoo\East\Website\Loader\CategoryLoader']]
      - ['setViewPath', ['%teknoo.east.website.view.category.list.file%']]
      - ['setTemplating', ['@templating.engine.twig']]

  teknoo.east.website.endpoint.admin.new.category:
    parent: 'teknoo.east.website.endpoint.admin.new.abstract'
    calls:
      - ['setWriter', ['@Teknoo\East\Website\Writer\CategoryWriter']]
      - ['setFormClass', ['%teknoo.east.website.form_type.category.class%']]
      - ['setViewPath', ['%teknoo.east.website.view.category.new.file%']]
      - ['setObjectClass', ['%teknoo.east.website.category.class%']]
      - ['setRouter', ['@router']]
      - ['setTemplating', ['@templating.engine.twig']]

  #Contents
  teknoo.east.website.endpoint.admin.delete.content:
    parent: 'teknoo.east.website.endpoint.admin.delete.abstract'
    calls:
      - ['setDeletingService', ['@teknoo.east.website.deleting.content']]
      - ['setLoader', ['@Teknoo\East\Website\Loader\ContentLoader']]
      - ['setRouter', ['@router']]

  teknoo.east.website.endpoint.admin.edit.content:
    parent: 'teknoo.east.website.endpoint.admin.edit.abstract'
    calls:
      - ['setLoader', ['@Teknoo\East\Website\Loader\ContentLoader']]
      - ['setWriter', ['@Teknoo\East\Website\Writer\ContentWriter']]
      - ['setFormClass', ['%teknoo.east.website.form_type.content.class%']]
      - ['setViewPath', ['%teknoo.east.website.view.content.edit.file%']]
      - ['setTemplating', ['@templating.engine.twig']]

  teknoo.east.website.endpoint.admin.list.content:
    parent: 'teknoo.east.website.endpoint.admin.list.abstract'
    calls:
      - ['setLoader', ['@Teknoo\East\Website\Loader\ContentLoader']]
      - ['setViewPath', ['%teknoo.east.website.view.content.list.file%']]
      - ['setTemplating', ['@templating.engine.twig']]

  teknoo.east.website.endpoint.admin.new.content:
    parent: 'teknoo.east.website.endpoint.admin.new.abstract'
    calls:
      - ['setWriter', ['@Teknoo\East\Website\Writer\ContentWriter']]
      - ['setFormClass', ['%teknoo.east.website.form_type.content.class%']]
      - ['setViewPath', ['%teknoo.east.website.view.content.new.file%']]
      - ['setObjectClass', ['%teknoo.east.website.content.class%']]
      - ['setRouter', ['@router']]
      - ['setTemplating', ['@templating.engine.twig']]

  #Media
  teknoo.east.website.endpoint.admin.delete.media:
    parent: 'teknoo.east.website.endpoint.admin.delete.abstract'
    calls:
      - ['setDeletingService', ['@teknoo.east.website.deleting.media']]
      - ['setLoader', ['@Teknoo\East\Website\Loader\MediaLoader']]
      - ['setRouter', ['@router']]

  teknoo.east.website.endpoint.admin.list.media:
    parent: 'teknoo.east.website.endpoint.admin.list.abstract'
    calls:
      - ['setLoader', ['@Teknoo\East\Website\Loader\MediaLoader']]
      - ['setViewPath', ['%teknoo.east.website.view.media.list.file%']]
      - ['setTemplating', ['@templating.engine.twig']]

  teknoo.east.website.endpoint.admin.new.media:
    parent: 'teknoo.east.website.endpoint.admin.new.abstract'
    calls:
      - ['setWriter', ['@Teknoo\East\Website\Writer\MediaWriter']]
      - ['setFormClass', ['%teknoo.east.website.form_type.media.class%']]
      - ['setViewPath', ['%teknoo.east.website.view.media.new.file%']]
      - ['setObjectClass', ['%teknoo.east.website.media.class%']]
      - ['setRouter', ['@router']]
      - ['setTemplating', ['@templating.engine.twig']]

  #Type
  teknoo.east.website.endpoint.admin.delete.type:
    parent: 'teknoo.east.website.endpoint.admin.delete.abstract'
    calls:
      - ['setDeletingService', ['@teknoo.east.website.deleting.type']]
      - ['setLoader', ['@Teknoo\East\Website\Loader\TypeLoader']]
      - ['setRouter', ['@router']]

  teknoo.east.website.endpoint.admin.edit.type:
    parent: 'teknoo.east.website.endpoint.admin.edit.abstract'
    calls:
      - ['setLoader', ['@Teknoo\East\Website\Loader\TypeLoader']]
      - ['setWriter', ['@Teknoo\East\Website\Writer\TypeWriter']]
      - ['setFormClass', ['%teknoo.east.website.form_type.type.class%']]
      - ['setViewPath', ['%teknoo.east.website.view.type.edit.file%']]
      - ['setTemplating', ['@templating.engine.twig']]

  teknoo.east.website.endpoint.admin.list.type:
    parent: 'teknoo.east.website.endpoint.admin.list.abstract'
    calls:
      - ['setLoader', ['@Teknoo\East\Website\Loader\TypeLoader']]
      - ['setViewPath', ['%teknoo.east.website.view.type.list.file%']]
      - ['setTemplating', ['@templating.engine.twig']]

  teknoo.east.website.endpoint.admin.new.type:
    parent: 'teknoo.east.website.endpoint.admin.new.abstract'
    calls:
      - ['setWriter', ['@Teknoo\East\Website\Writer\TypeWriter']]
      - ['setFormClass', ['%teknoo.east.website.form_type.type.class%']]
      - ['setViewPath', ['%teknoo.east.website.view.type.new.file%']]
      - ['setObjectClass', ['%teknoo.east.website.type.class%']]
      - ['setRouter', ['@router']]
      - ['setTemplating', ['@templating.engine.twig']]

  #User
  teknoo.east.website.endpoint.admin.delete.user:
    parent: 'teknoo.east.website.endpoint.admin.delete.abstract'
    calls:
      - ['setDeletingService', ['@teknoo.east.website.deleting.user']]
      - ['setLoader', ['@Teknoo\East\Website\Loader\UserLoader']]
      - ['setRouter', ['@router']]

  teknoo.east.website.endpoint.admin.edit.user:
    parent: 'teknoo.east.website.endpoint.admin.edit.abstract'
    calls:
      - ['setLoader', ['@Teknoo\East\Website\Loader\UserLoader']]
      - ['setWriter', ['@teknoo.east.website.bundle.writer.user']]
      - ['setFormClass', ['%teknoo.east.website.form_type.user.class%']]
      - ['setViewPath', ['%teknoo.east.website.view.user.edit.file%']]
      - ['setTemplating', ['@templating.engine.twig']]

  teknoo.east.website.endpoint.admin.list.user:
    parent: 'teknoo.east.website.endpoint.admin.list.abstract'
    calls:
      - ['setLoader', ['@Teknoo\East\Website\Loader\UserLoader']]
      - ['setViewPath', ['%teknoo.east.website.view.user.list.file%']]
      - ['setTemplating', ['@templating.engine.twig']]

  teknoo.east.website.endpoint.admin.new.user:
    parent: 'teknoo.east.website.endpoint.admin.new.abstract'
    calls:
      - ['setWriter', ['@teknoo.east.website.bundle.writer.user']]
      - ['setFormClass', ['%teknoo.east.website.form_type.user.class%']]
      - ['setViewPath', ['%teknoo.east.website.view.user.new.file%']]
      - ['setObjectClass', ['%teknoo.east.website.user.class%']]
      - ['setRouter', ['@router']]
      - ['setTemplating', ['@templating.engine.twig']]

  #Provider
  teknoo.east.website.bundle.user_provider:
    class: '%teknoo.east.website.bundle.user_provider.class%'
    arguments:
      - '@Teknoo\East\Website\Loader\UserLoader'

  #Command
  teknoo.east.website.bundle.command.create_user:
    class: '%teknoo.east.website.bundle.command.create_user.class%'
    arguments:
      - '@Teknoo\East\Website\Writer\UserWriter'
      - '@security.encoder_factory'
    tags:
      - { name: console.command }

  #Writer
  teknoo.east.website.bundle.writer.user:
    class: '%teknoo.east.website.bundle.writer.user.class%'
    arguments:
      - '@Teknoo\East\Website\Writer\UserWriter'
      - '@security.encoder_factory'
