parametres:
  teknoo.east.website.endpoint.content.class: 'Teknoo\East\WebsiteBundle\EndPoint\ContentEndPoint'
  teknoo.east.website.endpoint.media.class: 'Teknoo\East\WebsiteBundle\EndPoint\MediaEntPoint'

services:
  teknoo.east.website.endpoint.content:
    class: '%teknoo.east.website.endpoint.content.class%'
    autowire: true

  teknoo.east.website.endpoint.media:
    class: '%teknoo.east.website.endpoint.media.class%'
    autowire: true
