#infrastructures/doctrine/config/doctrine/Item.mongodb.yml
Teknoo\East\Website\Doctrine\Object\Item:
  type: 'documents'
  collection: 'items'
  referenceOne:
    parent:
      targetDocument: 'Teknoo\East\Website\Doctrine\Object\Item'
      cascade: 'all'
      inversedBy: 'children'
    content:
      targetDocument: 'Teknoo\East\Website\Doctrine\Object\Content'
      cascade: 'none'
  referenceMany:
    children:
      targetDocument:  'Teknoo\East\Website\Doctrine\Object\Item'
      cascade: 'all'
      mappedBy: 'parent'
  lifecycleCallbacks:
    postLoad: ['postLoadDoctrine']
