#infrastructures/doctrine/config/doctrine/Media.mongodb.yml
Teknoo\East\Website\Doctrine\Object\Media:
  type: 'documents'
  collection: 'media'
  fields:
    id:
      id: true
      type: 'string'
      strategy: 'UUID'
    name:
      type: 'string'
    mimeType:
      name: 'mime_type'
      type: 'string'
    file:
      type: 'file'
    length:
      type: 'int'
    alternative:
      type: 'string'
    createdAt:
      type: 'date'
      name: 'created_at'
      gedmo:
        timestampable:
          on: 'create'
    updatedAt:
      type: 'date'
      name: 'updated_at'
      gedmo:
        timestampable:
          on: 'update'
    deletedAt:
      type: 'date'
      name: 'deleted_at'
      nullable: true
      index: true
