#src/Resources/config/doctrine/Task.orm.yml
Teknoo\East\Website\Object\Content:
  type: 'documents'
  collection: 'contents'
  gedmo:
    soft_deleteable:
      field_name: 'deletedAt'
      time_aware: false
    translation:
      locale: 'localeField'
  fields:
    id:
      id: true
      type: 'string'
      strategy: 'UUID'
    title:
      type: 'string'
      gedmo:
        - 'translatable'
    subtitle:
      type: 'string'
      gedmo:
        - 'translatable'
    slug:
      type: 'string'
      index: true
      unique: true
      gedmo:
        slug:
          separator: '-'
          fields:
            - title
    parts:
      type: 'collection'
      gedmo:
        - 'translatable'
    tags:
      type: 'collection'
      index: true
    createdAt:
      type: 'date'
      name: 'created_at'
      index: true
      gedmo:
        timestampable:
          on: 'create'
    updatedAt:
      type: 'date'
      name: 'updated_at'
      index: true
      gedmo:
        timestampable:
          on: 'update'
    deletedAt:
      type: 'date'
      name: 'deleted_at'
      index: true
      nullable: true
    publishedAt:
      type: 'date'
      name: 'published_at'
      index: true
      nullable: true
  referenceOne:
    type:
      targetDocument: 'Teknoo\East\Website\Object\Type'
      cascade: 'all'
    author:
      targetDocument: 'Teknoo\East\Website\Object\User'
      cascade: 'all'
  referenceMany:
    categories:
      targetDocument:  'Teknoo\East\Website\Object\Category'
      cascade: 'all'
