#src/Resources/config/doctrine/Task.orm.yml
Teknoo\East\Website\Object\Media:
  type: 'documents'
  collection: 'media'
  gedmo:
    soft_deleteable:
      field_name: 'deletedAt'
      time_aware: false
  fields:
    id:
      id: true
      type: 'string'
      strategy: 'UUID'
    name:
      type: 'string'
    file:
      type: 'file'
    length:
      type: 'int'
    chunkSize:
      type: 'int'
      name: 'chunk_size'
    md5:
      type: 'string'
    mimeType:
      type: 'string'
      name: 'mime_type'
    alternative:
      type: 'string'
    createdAt:
      type: 'datetime'
      name: 'created_at'
      gedmo:
        timestampable:
          on: 'create'
    updatedAt:
      type: 'datetime'
      name: 'updated_at'
      gedmo:
        timestampable:
          on: 'update'
    deletedAt:
      type: 'datetime'
      name: 'deleted_at'
      nullable: true
      index: true
