#src/Resources/config/doctrine/Task.orm.yml
Teknoo\East\Website\Object\Type:
  type: 'documents'
  collection: 'types'
  gedmo:
    soft_deleteable:
      field_name: 'deletedAt'
      time_aware: false
  fields:
    id:
      id: true
      type: 'string'
      strategy: 'UUID'
    name:
      type: 'string'
    template:
      type: 'string'
    createdAt:
      type: 'datetime'
      name: 'created_at'
      gedmo:
        timestampable:
          on: 'create'
    updatedAt:
      type: 'datetime'
      name: 'updated_at'
      gedmo:
        timestampable:
          on: 'update'
    deletedAt:
      type: 'datetime'
      name: 'deleted_at'
      nullable: true
      index: true
