#infrastructures/doctrine/config/universal/Type.mongodb.yml
Teknoo\East\Website\Object\Type:
  type: 'documents'
  collection: 'types'
  fields:
    id:
      id: true
      type: 'string'
      strategy: 'UUID'
    name:
      type: 'string'
    template:
      type: 'string'
    blocks:
      type: 'hash'
    createdAt:
      type: 'date'
      name: 'created_at'
      gedmo:
        timestampable:
          on: 'create'
    updatedAt:
      type: 'date'
      name: 'updated_at'
      gedmo:
        timestampable:
          on: 'update'
    deletedAt:
      type: 'date'
      name: 'deleted_at'
      nullable: true
      index: true
