#infrastructures/doctrine/config/universal/User.mongodb.yml
Teknoo\East\Website\Object\User:
  type: 'documents'
  collection: 'users'
  gedmo:
    soft_deleteable:
      field_name: 'deletedAt'
      time_aware: false
  fields:
    id:
      id: true
      type: 'string'
      strategy: 'UUID'
    firstName:
      type: 'string'
      name: 'first_name'
    lastName:
      type: 'string'
      name: 'last_name'
    roles:
      type: 'collection'
    email:
      type: 'string'
      index: true
      unique: true
    password:
      type: 'string'
    salt:
      type: 'string'
    createdAt:
      type: 'date'
      name: 'created_at'
      gedmo:
        timestampable:
          on: 'create'
    updatedAt:
      type: 'date'
      name: 'updated_at'
      gedmo:
        timestampable:
          on: 'update'
    deletedAt:
      type: 'date'
      name: 'deleted_at'
      nullable: true
      index: true
