# user
_teknoo_common_admin_user_list:
    path: '/users'
    methods:  ['GET', 'POST']
    defaults:
        _controller: 'teknoo.east.common.endpoint.crud.list'
        loader: '@Teknoo\East\Common\Loader\UserLoader'
        defaultOrderDirection: 'ASC'
        itemsPerPage: 20
        template: '@@TeknooEastCommon/AdminUser/list.html.twig'
        errorTemplate: '@@TeknooEastCommon/Error/<error>.html.twig'

_teknoo_common_admin_user_edit:
    path: '/user/edit/{id}'
    methods:  ['GET', 'POST', 'PUT']
    defaults:
        _controller: 'teknoo.east.common.endpoint.crud.edit'
        loader: '@Teknoo\East\Common\Loader\UserLoader'
        writer: '@Teknoo\East\CommonBundle\Writer\SymfonyUserWriter'
        formClass: 'Teknoo\East\CommonBundle\Form\Type\UserType'
        template: '@@TeknooEastCommon/AdminUser/edit.html.twig'
        errorTemplate: '@@TeknooEastCommon/Error/<error>.html.twig'
        formOptions: {}

_teknoo_common_admin_user_new:
    path: '/user/new'
    methods:  ['GET', 'POST', 'PUT']
    defaults:
        _controller: 'teknoo.east.common.endpoint.crud.new'
        loader: '@Teknoo\East\Common\Loader\UserLoader'
        writer: '@Teknoo\East\CommonBundle\Writer\SymfonyUserWriter'
        objectClass: 'Teknoo\East\Common\Object\User'
        formClass: 'Teknoo\East\CommonBundle\Form\Type\UserType'
        template: '@@TeknooEastCommon/AdminUser/new.html.twig'
        errorTemplate: '@@TeknooEastCommon/Error/<error>.html.twig'
        route: '_teknoo_common_admin_user_edit'
        formOptions: {}

_teknoo_common_admin_user_delete:
    path: '/user/delete/{id}'
    methods:  ['GET', 'DELETE']
    defaults:
        _controller: 'teknoo.east.common.endpoint.crud.delete'
        loader: '@Teknoo\East\Common\Loader\UserLoader'
        deleter: '@teknoo.east.common.deleting.user'
        route: '_teknoo_common_admin_user_list'
        errorTemplate: '@@TeknooEastCommon/Error/<error>.html.twig'
