# item
_teknoo_website_admin_item_list:
    path: '/items/'
    methods:  ['GET', 'POST']
    defaults:
        _controller: 'teknoo.east.website.endpoint.crud.list'
        loader: '@Teknoo\East\Website\Loader\ItemLoader'
        defaultOrderDirection: 'ASC'
        itemsPerPage: 20
        template: '@@TeknooEastWebsite/AdminItem/list.html.twig'
        errorTemplate: '@@TeknooEastWebsite/Error/<error>.html.twig'

_teknoo_website_admin_item_edit:
    path: '/item/edit/{id}'
    methods:  ['GET', 'POST', 'PUT']
    defaults:
        _controller: 'teknoo.east.website.endpoint.crud.edit'
        loader: '@Teknoo\East\Website\Loader\ItemLoader'
        writer: '@Teknoo\East\Website\Writer\ItemWriter'
        formClass: 'Teknoo\East\Website\Doctrine\Form\Type\ItemType'
        template: '@@TeknooEastWebsite/AdminItem/edit.html.twig'
        errorTemplate: '@@TeknooEastWebsite/Error/<error>.html.twig'
        formOptions: { "doctrine_type": "%teknoo.east.website.form_type.doctrine.class%"}
        isTranslatable: true
        slugField: 'slug'

_teknoo_website_admin_item_new:
    path: '/item/new'
    methods:  ['GET', 'POST', 'PUT']
    defaults:
        _controller: 'teknoo.east.website.endpoint.crud.new'
        loader: '@Teknoo\East\Website\Loader\ItemLoader'
        writer: '@Teknoo\East\Website\Writer\ItemWriter'
        objectClass: 'Teknoo\East\Website\Doctrine\Object\Item'
        formClass: 'Teknoo\East\Website\Doctrine\Form\Type\ItemType'
        template: '@@TeknooEastWebsite/AdminItem/new.html.twig'
        errorTemplate: '@@TeknooEastWebsite/Error/<error>.html.twig'
        formOptions: { "doctrine_type": "%teknoo.east.website.form_type.doctrine.class%"}
        route: '_teknoo_website_admin_item_edit'
        isTranslatable: true
        slugField: 'slug'

_teknoo_website_admin_item_delete:
    path: '/item/delete/{id}'
    methods:  ['GET', 'DELETE']
    defaults:
        _controller: 'teknoo.east.website.endpoint.crud.delete'
        loader: '@Teknoo\East\Website\Loader\ItemLoader'
        deleter: '@teknoo.east.website.deleting.item'
        route: '_teknoo_website_admin_item_list'
        errorTemplate: '@@TeknooEastWebsite/Error/<error>.html.twig'

# content
_teknoo_website_admin_content_list:
    path: '/contents/'
    methods:  ['GET', 'POST']
    defaults:
        _controller: 'teknoo.east.website.endpoint.crud.list'
        loader: '@Teknoo\East\Website\Loader\ContentLoader'
        defaultOrderDirection: 'ASC'
        itemsPerPage: 20
        template: '@@TeknooEastWebsite/AdminContent/list.html.twig'
        errorTemplate: '@@TeknooEastWebsite/Error/<error>.html.twig'

_teknoo_website_admin_content_edit:
    path: '/content/edit/{id}'
    methods:  ['GET', 'POST', 'PUT']
    defaults:
        _controller: 'teknoo.east.website.endpoint.crud.edit'
        loader: '@Teknoo\East\Website\Loader\ContentLoader'
        writer: '@Teknoo\East\Website\Writer\ContentWriter'
        formClass: 'Teknoo\East\Website\Doctrine\Form\Type\ContentType'
        template: '@@TeknooEastWebsite/AdminContent/edit.html.twig'
        errorTemplate: '@@TeknooEastWebsite/Error/<error>.html.twig'
        formOptions: { "doctrine_type": "%teknoo.east.website.form_type.doctrine.class%"}
        isTranslatable: true
        slugField: 'slug'

_teknoo_website_admin_content_new:
    path: '/content/new'
    methods:  ['GET', 'POST', 'PUT']
    defaults:
        _controller: 'teknoo.east.website.endpoint.crud.new'
        loader: '@Teknoo\East\Website\Loader\ContentLoader'
        writer: '@Teknoo\East\Website\Writer\ContentWriter'
        objectClass: 'Teknoo\East\Website\Doctrine\Object\Content'
        formClass: 'Teknoo\East\Website\Doctrine\Form\Type\ContentType'
        template: '@@TeknooEastWebsite/AdminContent/new.html.twig'
        errorTemplate: '@@TeknooEastWebsite/Error/<error>.html.twig'
        formOptions: { "doctrine_type": "%teknoo.east.website.form_type.doctrine.class%"}
        route: '_teknoo_website_admin_content_edit'
        isTranslatable: true
        slugField: 'slug'

_teknoo_website_admin_content_delete:
    path: '/content/delete/{id}'
    methods:  ['GET', 'DELETE']
    defaults:
        _controller: 'teknoo.east.website.endpoint.crud.delete'
        loader: '@Teknoo\East\Website\Loader\ContentLoader'
        deleter: '@teknoo.east.website.deleting.content'
        route: '_teknoo_website_admin_content_list'
        errorTemplate: '@@TeknooEastWebsite/Error/<error>.html.twig'

# media
_teknoo_website_admin_media_list:
    path: '/media/'
    methods:  ['GET', 'POST']
    defaults:
        _controller: 'teknoo.east.website.endpoint.crud.list'
        loader: '@Teknoo\East\Website\Loader\MediaLoader'
        defaultOrderDirection: 'ASC'
        itemsPerPage: 20
        template: '@@TeknooEastWebsite/AdminMedia/list.html.twig'
        errorTemplate: '@@TeknooEastWebsite/Error/<error>.html.twig'

_teknoo_website_admin_media_new:
    path: '/media/new'
    methods:  ['GET', 'POST', 'PUT']
    defaults:
        _controller: 'teknoo.east.website.endpoint.crud.new'
        loader: '@Teknoo\East\Website\Loader\MediaLoader'
        writer: '@Teknoo\East\Website\Doctrine\Writer\ODM\MediaWriter'
        objectClass: 'Teknoo\East\Website\Doctrine\Object\Media'
        formClass: 'Teknoo\East\WebsiteBundle\Form\Type\MediaType'
        template: '@@TeknooEastWebsite/AdminMedia/new.html.twig'
        errorTemplate: '@@TeknooEastWebsite/Error/<error>.html.twig'
        formOptions: { }
        route: '_teknoo_website_admin_media_list'

_teknoo_website_admin_media_delete:
    path: '/media/delete/{id}'
    methods:  ['GET', 'DELETE']
    defaults:
        _controller: 'teknoo.east.website.endpoint.crud.delete'
        loader: '@Teknoo\East\Website\Loader\MediaLoader'
        deleter: '@teknoo.east.website.deleting.media'
        route: '_teknoo_website_admin_media_list'
        errorTemplate: '@@TeknooEastWebsite/Error/<error>.html.twig'

# type
_teknoo_website_admin_type_list:
    path: '/types/'
    methods:  ['GET', 'POST']
    defaults:
        _controller: 'teknoo.east.website.endpoint.crud.list'
        loader: '@Teknoo\East\Website\Loader\TypeLoader'
        defaultOrderDirection: 'ASC'
        itemsPerPage: 20
        template: '@@TeknooEastWebsite/AdminType/list.html.twig'
        errorTemplate: '@@TeknooEastWebsite/Error/<error>.html.twig'

_teknoo_website_admin_type_edit:
    path: '/type/edit/{id}'
    methods:  ['GET', 'POST', 'PUT']
    defaults:
        _controller: 'teknoo.east.website.endpoint.crud.edit'
        loader: '@Teknoo\East\Website\Loader\TypeLoader'
        writer: '@Teknoo\East\Website\Writer\TypeWriter'
        formClass: 'Teknoo\East\WebsiteBundle\Form\Type\TypeType'
        template: '@@TeknooEastWebsite/AdminType/edit.html.twig'
        errorTemplate: '@@TeknooEastWebsite/Error/<error>.html.twig'
        formOptions: { }

_teknoo_website_admin_type_new:
    path: '/type/new'
    methods:  ['GET', 'POST', 'PUT']
    defaults:
        _controller: 'teknoo.east.website.endpoint.crud.new'
        loader: '@Teknoo\East\Website\Loader\TypeLoader'
        writer: '@Teknoo\East\Website\Writer\TypeWriter'
        objectClass: 'Teknoo\East\Website\Object\Type'
        formClass: 'Teknoo\East\WebsiteBundle\Form\Type\TypeType'
        template: '@@TeknooEastWebsite/AdminType/new.html.twig'
        errorTemplate: '@@TeknooEastWebsite/Error/<error>.html.twig'
        route: '_teknoo_website_admin_type_edit'
        formOptions: { }

_teknoo_website_admin_type_delete:
    path: '/type/delete/{id}'
    methods:  ['GET', 'DELETE']
    defaults:
        _controller: 'teknoo.east.website.endpoint.crud.delete'
        loader: '@Teknoo\East\Website\Loader\TypeLoader'
        deleter: '@teknoo.east.website.deleting.type'
        route: '_teknoo_website_admin_type_list'
        errorTemplate: '@@TeknooEastWebsite/Error/<error>.html.twig'

# user
_teknoo_website_admin_user_list:
    path: '/users/'
    methods:  ['GET', 'POST']
    defaults:
        _controller: 'teknoo.east.website.endpoint.crud.list'
        loader: '@Teknoo\East\Website\Loader\UserLoader'
        defaultOrderDirection: 'ASC'
        itemsPerPage: 20
        template: '@@TeknooEastWebsite/AdminUser/list.html.twig'
        errorTemplate: '@@TeknooEastWebsite/Error/<error>.html.twig'

_teknoo_website_admin_user_edit:
    path: '/user/edit/{id}'
    methods:  ['GET', 'POST', 'PUT']
    defaults:
        _controller: 'teknoo.east.website.endpoint.crud.edit'
        loader: '@Teknoo\East\Website\Loader\UserLoader'
        writer: '@Teknoo\East\WebsiteBundle\Writer\SymfonyUserWriter'
        formClass: 'Teknoo\East\WebsiteBundle\Form\Type\UserType'
        template: '@@TeknooEastWebsite/AdminUser/edit.html.twig'
        errorTemplate: '@@TeknooEastWebsite/Error/<error>.html.twig'
        formOptions: {}

_teknoo_website_admin_user_new:
    path: '/user/new'
    methods:  ['GET', 'POST', 'PUT']
    defaults:
        _controller: 'teknoo.east.website.endpoint.crud.new'
        loader: '@Teknoo\East\Website\Loader\UserLoader'
        writer: '@Teknoo\East\WebsiteBundle\Writer\SymfonyUserWriter'
        objectClass: 'Teknoo\East\Website\Object\User'
        formClass: 'Teknoo\East\WebsiteBundle\Form\Type\UserType'
        template: '@@TeknooEastWebsite/AdminUser/new.html.twig'
        errorTemplate: '@@TeknooEastWebsite/Error/<error>.html.twig'
        route: '_teknoo_website_admin_user_edit'
        formOptions: {}

_teknoo_website_admin_user_delete:
    path: '/user/delete/{id}'
    methods:  ['GET', 'DELETE']
    defaults:
        _controller: 'teknoo.east.website.endpoint.crud.delete'
        loader: '@Teknoo\East\Website\Loader\UserLoader'
        deleter: '@teknoo.east.website.deleting.user'
        route: '_teknoo_website_admin_user_list'
        errorTemplate: '@@TeknooEastWebsite/Error/<error>.html.twig'
