# user
_teknoo_common_admin_user_list:
    path: '/users'
    methods:  ['GET', 'POST']
    defaults:
        _controller: 'teknoo.east.common.endpoint.crud.list'
        defaultOrderDirection: 'ASC'
        errorTemplate: '@@TeknooEastCommon/Error/<error>.html.twig'
        itemsPerPage: 20
        loader: '@Teknoo\East\Common\Loader\UserLoader'
        template: '@@TeknooEastCommon/AdminUser/list.html.twig'

_teknoo_common_admin_user_edit:
    path: '/user/edit/{id}'
    methods:  ['GET', 'POST', 'PUT']
    defaults:
        _controller: 'teknoo.east.common.endpoint.crud.edit'
        errorTemplate: '@@TeknooEastCommon/Error/<error>.html.twig'
        formClass: 'Teknoo\East\CommonBundle\Form\Type\UserType'
        formOptions: {}
        loader: '@Teknoo\East\Common\Loader\UserLoader'
        template: '@@TeknooEastCommon/AdminUser/edit.html.twig'
        writer: '@Teknoo\East\CommonBundle\Writer\SymfonyUserWriter'

_teknoo_common_admin_user_new:
    path: '/user/new'
    methods:  ['GET', 'POST', 'PUT']
    defaults:
        _controller: 'teknoo.east.common.endpoint.crud.new'
        errorTemplate: '@@TeknooEastCommon/Error/<error>.html.twig'
        formClass: 'Teknoo\East\CommonBundle\Form\Type\UserType'
        formOptions: {}
        loader: '@Teknoo\East\Common\Loader\UserLoader'
        objectClass: 'Teknoo\East\Common\Object\User'
        route: '_teknoo_common_admin_user_edit'
        template: '@@TeknooEastCommon/AdminUser/new.html.twig'
        writer: '@Teknoo\East\CommonBundle\Writer\SymfonyUserWriter'

_teknoo_common_admin_user_delete:
    path: '/user/delete/{id}'
    methods:  ['GET', 'DELETE']
    defaults:
        _controller: 'teknoo.east.common.endpoint.crud.delete'
        deleter: '@teknoo.east.common.deleting.user'
        errorTemplate: '@@TeknooEastCommon/Error/<error>.html.twig'
        loader: '@Teknoo\East\Common\Loader\UserLoader'
        route: '_teknoo_common_admin_user_list'

# media
_teknoo_common_admin_media_list:
    path: '/media'
    methods:  ['GET', 'POST']
    defaults:
        _controller: 'teknoo.east.common.endpoint.crud.list'
        defaultOrderDirection: 'ASC'
        errorTemplate: '@@TeknooEastCommon/Error/<error>.html.twig'
        itemsPerPage: 20
        loader: '@Teknoo\East\Common\Loader\MediaLoader'
        template: '@@TeknooEastCommon/AdminMedia/list.html.twig'

_teknoo_common_admin_media_new:
    path: '/media/new'
    methods:  ['GET', 'POST', 'PUT']
    defaults:
        _controller: 'teknoo.east.common.endpoint.crud.new'
        errorTemplate: '@@TeknooEastCommon/Error/<error>.html.twig'
        formClass: 'Teknoo\East\CommonBundle\Form\Type\MediaType'
        formOptions: { }
        loader: '@Teknoo\East\Common\Loader\MediaLoader'
        objectClass: 'Teknoo\East\Common\Doctrine\Object\Media'
        route: '_teknoo_common_admin_media_list'
        template: '@@TeknooEastCommon/AdminMedia/new.html.twig'
        writer: '@Teknoo\East\Common\Doctrine\Writer\ODM\MediaWriter'

_teknoo_common_admin_media_delete:
    path: '/media/delete/{id}'
    methods:  ['GET', 'DELETE']
    defaults:
        _controller: 'teknoo.east.common.endpoint.crud.delete'
        deleter: '@teknoo.east.common.deleting.media'
        errorTemplate: '@@TeknooEastCommon/Error/<error>.html.twig'
        loader: '@Teknoo\East\Common\Loader\MediaLoader'
        route: '_teknoo_common_admin_media_list'