_teknoo_website_admin_item_list:
    path: '/items/'
    methods:  ['GET']
    defaults: { _controller: 'teknoo.east.website.endpoint.admin.list.item' }

_teknoo_website_admin_item_edit:
    path: '/item/edit/{id}'
    methods:  ['GET', 'POST', 'PUT']
    defaults: { _controller: 'teknoo.east.website.endpoint.admin.edit.item', isTranslatable: true }

_teknoo_website_admin_item_new:
    path: '/item/new'
    methods:  ['GET', 'POST', 'PUT']
    defaults: { _controller: 'teknoo.east.website.endpoint.admin.new.item', editRoute: '_teknoo_website_admin_item_edit', isTranslatable: true  }

_teknoo_website_admin_item_delete:
    path: '/item/delete/{id}'
    methods:  ['GET', 'DELETE']
    defaults: { _controller: 'teknoo.east.website.endpoint.admin.delete.item', nextRoute: '_teknoo_website_admin_item_list'}

_teknoo_website_admin_content_list:
    path: '/contents/'
    methods:  ['GET']
    defaults: { _controller: 'teknoo.east.website.endpoint.admin.list.content' }

_teknoo_website_admin_content_edit:
    path: '/content/edit/{id}'
    methods:  ['GET', 'POST', 'PUT']
    defaults: { _controller: 'teknoo.east.website.endpoint.admin.edit.content', isTranslatable: true }

_teknoo_website_admin_content_new:
    path: '/content/new'
    methods:  ['GET', 'POST', 'PUT']
    defaults: { _controller: 'teknoo.east.website.endpoint.admin.new.content', editRoute: '_teknoo_website_admin_content_edit', isTranslatable: true }

_teknoo_website_admin_content_delete:
    path: '/content/delete/{id}'
    methods:  ['GET', 'DELETE']
    defaults: { _controller: 'teknoo.east.website.endpoint.admin.delete.content', nextRoute: '_teknoo_website_admin_content_list' }

_teknoo_website_admin_media_list:
    path: '/media/'
    methods:  ['GET']
    defaults: { _controller: 'teknoo.east.website.endpoint.admin.list.media' }

_teknoo_website_admin_media_new:
    path: '/media/new'
    methods:  ['GET', 'POST', 'PUT']
    defaults: { _controller: 'teknoo.east.website.endpoint.admin.new.media', editRoute: '_teknoo_website_admin_media_list' }

_teknoo_website_admin_media_delete:
    path: '/media/delete/{id}'
    methods:  ['GET', 'DELETE']
    defaults: { _controller: 'teknoo.east.website.endpoint.admin.delete.media', nextRoute: '_teknoo_website_admin_media_list' }

_teknoo_website_admin_type_list:
    path: '/types/'
    methods:  ['GET']
    defaults: { _controller: 'teknoo.east.website.endpoint.admin.list.type' }

_teknoo_website_admin_type_edit:
    path: '/type/edit/{id}'
    methods:  ['GET', 'POST', 'PUT']
    defaults: { _controller: 'teknoo.east.website.endpoint.admin.edit.type' }

_teknoo_website_admin_type_new:
    path: '/type/new'
    methods:  ['GET', 'POST', 'PUT']
    defaults: { _controller: 'teknoo.east.website.endpoint.admin.new.type', editRoute: '_teknoo_website_admin_type_edit' }

_teknoo_website_admin_type_delete:
    path: '/type/delete/{id}'
    methods:  ['GET', 'DELETE']
    defaults: { _controller: 'teknoo.east.website.endpoint.admin.delete.type', nextRoute: '_teknoo_website_admin_type_list' }

_teknoo_website_admin_user_list:
    path: '/users/'
    methods:  ['GET']
    defaults: { _controller: 'teknoo.east.website.endpoint.admin.list.user' }

_teknoo_website_admin_user_edit:
    path: '/user/edit/{id}'
    methods:  ['GET', 'POST', 'PUT']
    defaults: { _controller: 'teknoo.east.website.endpoint.admin.edit.user' }

_teknoo_website_admin_user_new:
    path: '/user/new'
    methods:  ['GET', 'POST', 'PUT']
    defaults: { _controller: 'teknoo.east.website.endpoint.admin.new.user', editRoute: '_teknoo_website_admin_user_edit' }

_teknoo_website_admin_user_delete:
    path: '/user/delete/{id}'
    methods:  ['GET', 'DELETE']
    defaults: { _controller: 'teknoo.east.website.endpoint.admin.delete.user', nextRoute: '_teknoo_website_admin_user_list' }
