_teknoo_common_media:
    path: '/media/{id}'
    methods:  ['GET']
    defaults:
        _controller: 'teknoo.east.common.endpoint.media'
        errorTemplate: '@@TeknooEastCommon/Error/<error>.html.twig'
