parameters:
    #Admin form types
    teknoo.east.common.form_type.doctrine.class: 'Doctrine\Bundle\MongoDBBundle\Form\Type\DocumentType'

    #Command
    teknoo.east.common.bundle.command.create_user.class: 'Teknoo\East\CommonBundle\Command\CreateUserCommand'

    #Provider
    teknoo.east.common.bundle.password_authenticated_user_provider.class: 'Teknoo\East\CommonBundle\Provider\PasswordAuthenticatedUserProvider'
    teknoo.east.common.bundle.third_party_authenticated_user_provider.class: 'Teknoo\East\CommonBundle\Provider\ThirdPartyAuthenticatedUserProvider'
    teknoo.east.common.bundle.user_with_recovery_access_provider.class: 'Teknoo\East\CommonBundle\Provider\RecoveringAccessUserProvider'
    teknoo.east.common.bundle.password_authenticated_user_provider.default_algo: 'sodium'

    #Authenticator
    teknoo.east.common.bundle.security.authenticator.oauth2.class: 'Teknoo\East\CommonBundle\Security\Authenticator\OAuth2Authenticator'

    #Writer
    teknoo.east.common.bundle.writer.user.class: 'Teknoo\East\CommonBundle\Writer\SymfonyUserWriter'

    teknoo.east.common.bundle.recovery.notification.subject: 'teknoo.space.common.recovery_access.notification.subject'
    teknoo.east.common.bundle.recovery.role: 'ROLE_RECOVERY'
    teknoo.east.common.bundle.recovery.notification_class: 'Symfony\Component\Security\Http\LoginLink\LoginLinkNotification'

    #Assets
    teknoo.east.common.assets.no_overwrite: true

    #Rendering
    teknoo.east.common.rendering.clean_html: false
    teknoo.east.common.admin.rendering.clean_html: true

    #Steps
    teknoo.east.common.bundle.allowed_forms: []

    #Bowls
    teknoo.east.common.endpoint.2fa_totp_disable.class: 'Teknoo\Recipe\Bowl\FiberRecipeBowl'
    teknoo.east.common.endpoint.2fa_totp_enable.class: 'Teknoo\Recipe\Bowl\FiberRecipeBowl'
    teknoo.east.common.endpoint.2fa_totp_qrcode.class: 'Teknoo\Recipe\Bowl\FiberRecipeBowl'
    teknoo.east.common.endpoint.2fa_totp_validate.class: 'Teknoo\Recipe\Bowl\FiberRecipeBowl'
    teknoo.east.common.endpoint.crud.delete.bowl.class: 'Teknoo\Recipe\Bowl\FiberRecipeBowl'
    teknoo.east.common.endpoint.crud.edit.bowl.class: 'Teknoo\Recipe\Bowl\FiberRecipeBowl'
    teknoo.east.common.endpoint.crud.list.bowl.class: 'Teknoo\Recipe\Bowl\FiberRecipeBowl'
    teknoo.east.common.endpoint.crud.new.bowl.class: 'Teknoo\Recipe\Bowl\FiberRecipeBowl'
    teknoo.east.common.endpoint.media.bowl.class: 'Teknoo\Recipe\Bowl\FiberRecipeBowl'
    teknoo.east.common.endpoint.minifier.bowl.class: 'Teknoo\Recipe\Bowl\FiberRecipeBowl'
    teknoo.east.common.endpoint.static.bowl.class: 'Teknoo\Recipe\Bowl\RecipeBowl'
    teknoo.east.common.endpoint.user_recovery.prepare.bowl.class: 'Teknoo\Recipe\Bowl\FiberRecipeBowl'

services:
    #Generic Endpoints
    teknoo.east.common.endpoint.static.bowl:
        class: '%teknoo.east.common.endpoint.static.bowl.class%'
        arguments:
            - '@Teknoo\East\Common\Contracts\Recipe\Plan\RenderStaticContentEndPointInterface'
            - 0

    teknoo.east.common.endpoint.static:
        class: 'Teknoo\East\Foundation\EndPoint\RecipeEndPoint'
        public: true
        arguments:
            - '@teknoo.east.common.endpoint.static.bowl'
            - '@service_container'

    #2FA
    teknoo.east.common.endpoint.2fa_totp_enable.bowl:
        class: '%teknoo.east.common.endpoint.2fa_totp_enable.class%'
        arguments:
            - '@Teknoo\East\CommonBundle\Recipe\Plan\Enable2FA'
            - 0

    teknoo.east.common.endpoint.2fa_totp_enable:
        class: 'Teknoo\East\Foundation\EndPoint\RecipeEndPoint'
        public: true
        arguments:
            - '@teknoo.east.common.endpoint.2fa_totp_enable.bowl'
            - '@service_container'

    teknoo.east.common.endpoint.2fa_totp_disable.bowl:
        class: '%teknoo.east.common.endpoint.2fa_totp_disable.class%'
        arguments:
            - '@Teknoo\East\CommonBundle\Recipe\Plan\Disable2FA'
            - 0

    teknoo.east.common.endpoint.2fa_totp_disable:
        class: 'Teknoo\East\Foundation\EndPoint\RecipeEndPoint'
        public: true
        arguments:
            - '@teknoo.east.common.endpoint.2fa_totp_disable.bowl'
            - '@service_container'

    teknoo.east.common.endpoint.2fa_totp_qrcode.bowl:
        class: '%teknoo.east.common.endpoint.2fa_totp_qrcode.class%'
        arguments:
            - '@Teknoo\East\CommonBundle\Recipe\Plan\GenerateQRCode'
            - 0

    teknoo.east.common.endpoint.2fa_totp_qrcode:
        class: 'Teknoo\East\Foundation\EndPoint\RecipeEndPoint'
        public: true
        arguments:
            - '@teknoo.east.common.endpoint.2fa_totp_qrcode.bowl'
            - '@service_container'

    teknoo.east.common.endpoint.2fa_totp_validate.bowl:
        class: '%teknoo.east.common.endpoint.2fa_totp_validate.class%'
        arguments:
            - '@Teknoo\East\CommonBundle\Recipe\Plan\Validate2FA'
            - 0

    teknoo.east.common.endpoint.2fa_totp_validate:
        class: 'Teknoo\East\Foundation\EndPoint\RecipeEndPoint'
        public: true
        arguments:
            - '@teknoo.east.common.endpoint.2fa_totp_validate.bowl'
            - '@service_container'

    #CRUD endpoints
    teknoo.east.common.endpoint.crud.delete.bowl:
        class: '%teknoo.east.common.endpoint.crud.delete.bowl.class%'
        arguments:
            - '@Teknoo\East\Common\Contracts\Recipe\Plan\DeleteObjectEndPointInterface'
            - 0

    teknoo.east.common.endpoint.crud.delete:
        class: 'Teknoo\East\Foundation\EndPoint\RecipeEndPoint'
        public: true
        arguments:
            - '@teknoo.east.common.endpoint.crud.delete.bowl'
            - '@service_container'

    teknoo.east.common.endpoint.crud.edit.bowl:
        class: '%teknoo.east.common.endpoint.crud.edit.bowl.class%'
        arguments:
            - '@Teknoo\East\Common\Contracts\Recipe\Plan\EditObjectEndPointInterface'
            - 0

    teknoo.east.common.endpoint.crud.edit:
        class: 'Teknoo\East\Foundation\EndPoint\RecipeEndPoint'
        public: true
        arguments:
            - '@teknoo.east.common.endpoint.crud.edit.bowl'
            - '@service_container'

    teknoo.east.common.endpoint.crud.list.bowl:
        class: '%teknoo.east.common.endpoint.crud.list.bowl.class%'
        arguments:
            - '@Teknoo\East\Common\Contracts\Recipe\Plan\ListObjectEndPointInterface'
            - 0

    teknoo.east.common.endpoint.crud.list:
        class: 'Teknoo\East\Foundation\EndPoint\RecipeEndPoint'
        public: true
        arguments:
            - '@teknoo.east.common.endpoint.crud.list.bowl'
            - '@service_container'
            - { criteria: [] }

    teknoo.east.common.endpoint.crud.new.bowl:
        class: '%teknoo.east.common.endpoint.crud.new.bowl.class%'
        arguments:
            - '@Teknoo\East\Common\Contracts\Recipe\Plan\CreateObjectEndPointInterface'
            - 0

    teknoo.east.common.endpoint.crud.new:
        class: 'Teknoo\East\Foundation\EndPoint\RecipeEndPoint'
        public: true
        arguments:
            - '@teknoo.east.common.endpoint.crud.new.bowl'
            - '@service_container'

    #Media
    teknoo.east.common.endpoint.media.bowl:
        class: '%teknoo.east.common.endpoint.media.bowl.class%'
        arguments:
            - '@Teknoo\East\Common\Contracts\Recipe\Plan\RenderMediaEndPointInterface'
            - 0

    teknoo.east.common.endpoint.media:
        class: 'Teknoo\East\Foundation\EndPoint\RecipeEndPoint'
        public: true
        arguments:
            - '@teknoo.east.common.endpoint.media.bowl'
            - '@service_container'

    #Minifier
    teknoo.east.common.endpoint.minifier.bowl:
        class: '%teknoo.east.common.endpoint.minifier.bowl.class%'
        arguments:
            - '@Teknoo\East\Common\Contracts\Recipe\Plan\MinifierEndPointInterface'
            - 0

    teknoo.east.common.endpoint.minifier:
        class: 'Teknoo\East\Foundation\EndPoint\RecipeEndPoint'
        public: true
        arguments:
            - '@teknoo.east.common.endpoint.minifier.bowl'
            - '@service_container'

    #User Recovery
    teknoo.east.common.endpoint.user_recovery.prepare.bowl:
        class: '%teknoo.east.common.endpoint.user_recovery.prepare.bowl.class%'
        arguments:
            - '@Teknoo\East\Common\Contracts\Recipe\Plan\PrepareRecoveryAccessEndPointInterface'
            - 0

    teknoo.east.common.endpoint.user_recovery.prepare:
        class: 'Teknoo\East\Foundation\EndPoint\RecipeEndPoint'
        public: true
        arguments:
            - '@teknoo.east.common.endpoint.user_recovery.prepare.bowl'
            - '@service_container'

    #Steps
    Teknoo\East\CommonBundle\Recipe\Step\SearchFormLoader:
        class: 'Teknoo\East\CommonBundle\Recipe\Step\SearchFormLoader'
        arguments:
            - '@form.factory'
            - '%teknoo.east.common.bundle.allowed_forms%'
        public: true

    Teknoo\East\CommonBundle\Recipe\Step\FormHandling:
        class: 'Teknoo\East\CommonBundle\Recipe\Step\FormHandling'
        arguments:
            - '@Teknoo\East\Foundation\Time\DatesService'
            - '@form.factory'
        public: true

    Teknoo\East\CommonBundle\Recipe\Step\RedirectClient:
        class: 'Teknoo\East\CommonBundle\Recipe\Step\RedirectClient'
        arguments:
            - '@Psr\Http\Message\ResponseFactoryInterface'
            - '@router'
        public: true

    Teknoo\East\CommonBundle\Recipe\Step\EnableTOTP:
        class: 'Teknoo\East\CommonBundle\Recipe\Step\EnableTOTP'
        public: true
        arguments:
            - '@Teknoo\East\CommonBundle\Writer\SymfonyUserWriter'
            - '@security.token_storage'

    Teknoo\East\CommonBundle\Recipe\Step\DisableTOTP:
        class: 'Teknoo\East\CommonBundle\Recipe\Step\DisableTOTP'
        public: true
        arguments:
            - '@Teknoo\East\CommonBundle\Writer\SymfonyUserWriter'
            - '@security.token_storage'

    Teknoo\East\CommonBundle\Recipe\Step\GenerateQRCodeTextForTOTP:
        class: 'Teknoo\East\CommonBundle\Recipe\Step\GenerateQRCodeTextForTOTP'
        public: true
        arguments:
            - '@security.token_storage'

    Teknoo\East\CommonBundle\Recipe\Step\ValidateTOTP:
        class: 'Teknoo\East\CommonBundle\Recipe\Step\ValidateTOTP'
        public: true
        arguments:
            - '@Teknoo\East\CommonBundle\Writer\SymfonyUserWriter'
            - '@security.token_storage'

    Teknoo\East\Common\Contracts\Recipe\Step\User\NotifyUserAboutRecoveryAccessInterface:
        alias: 'Teknoo\East\CommonBundle\Recipe\Step\RecoveryAccessNotification'
        public: true

    Teknoo\East\CommonBundle\Recipe\Step\RecoveryAccessNotification:
        class: 'Teknoo\East\CommonBundle\Recipe\Step\RecoveryAccessNotification'
        public: true
        arguments:
            - '@?Symfony\Component\Security\Http\LoginLink\LoginLinkHandlerInterface'
            - '@?notifier'
            - '@?translator'
            - '%teknoo.east.common.bundle.recovery.notification.subject%'
            - '%teknoo.east.common.bundle.recovery.role%'

    #Provider
    Teknoo\East\CommonBundle\Provider\PasswordAuthenticatedUserProvider:
        class: '%teknoo.east.common.bundle.password_authenticated_user_provider.class%'
        arguments:
            - '@Teknoo\East\Common\Loader\UserLoader'
            - '@Teknoo\East\CommonBundle\Writer\SymfonyUserWriter'

    Teknoo\East\CommonBundle\Provider\ThirdPartyAuthenticatedUserProvider:
        class: '%teknoo.east.common.bundle.third_party_authenticated_user_provider.class%'
        arguments:
            - '@Teknoo\East\Common\Loader\UserLoader'


    Teknoo\East\CommonBundle\Provider\RecoveringAccessUserProvider:
        class: '%teknoo.east.common.bundle.user_with_recovery_access_provider.class%'
        arguments:
            - '@Teknoo\East\Common\Loader\UserLoader'
            - '@Teknoo\East\CommonBundle\Writer\SymfonyUserWriter'
            - '@Teknoo\East\Foundation\Time\DatesService'
            - '%teknoo.east.common.bundle.recovery.role%'

    #Command
    Teknoo\East\CommonBundle\Command\CreateUserCommand:
        class: '%teknoo.east.common.bundle.command.create_user.class%'
        arguments:
            - '@Teknoo\East\Common\Writer\UserWriter'
            - '@security.user_password_hasher'
        tags:
            - { name: console.command }
        public: false

    #Authenticator
    Teknoo\East\CommonBundle\Contracts\Security\Authenticator\UserConverterInterface:
        public: true
        synthetic: true

    Teknoo\East\CommonBundle\Security\Authenticator\OAuth2Authenticator:
        class: '%teknoo.east.common.bundle.security.authenticator.oauth2.class%'
        arguments:
            - '@KnpU\OAuth2ClientBundle\Client\ClientRegistry'
            - '@Teknoo\East\Common\Loader\UserLoader'
            - '@Teknoo\East\CommonBundle\Writer\SymfonyUserWriter'
            - '@Teknoo\East\CommonBundle\Contracts\Security\Authenticator\UserConverterInterface'

    #Writer
    Teknoo\East\CommonBundle\Writer\SymfonyUserWriter:
        class: '%teknoo.east.common.bundle.writer.user.class%'
        arguments:
            - '@Teknoo\East\Common\Writer\UserWriter'
            - '@security.user_password_hasher'
        public: true

    #Form
    Teknoo\East\CommonBundle\Form\Type\TOTPType:
        class: 'Teknoo\East\CommonBundle\Form\Type\TOTPType'
        arguments:
            - '@security.token_storage'
            - '@?scheb_two_factor.security.totp_authenticator'
            - '@?scheb_two_factor.security.google_authenticator'
        tags:
            - { name: form.type }

    #Commands
    teknoo.east.command.symfony.command.minify_css:
        parent: 'Teknoo\East\CommonBundle\Command\MinifyCommand:css'
        tags:
            - { name: 'console.command' }

    teknoo.east.command.symfony.command.minify_js:
        parent: 'Teknoo\East\CommonBundle\Command\MinifyCommand:js'
        tags:
            - { name: 'console.command' }
