parameters:
    #Admin form types
    teknoo.east.website.form_type.doctrine.class: 'Doctrine\Bundle\MongoDBBundle\Form\Type\DocumentType'

    #Command
    teknoo.east.website.bundle.command.create_user.class: 'Teknoo\East\WebsiteBundle\Command\CreateUserCommand'

    #Provider
    teknoo.east.website.bundle.password_authenticated_user_provider.class: 'Teknoo\East\WebsiteBundle\Provider\PasswordAuthenticatedUserProvider'
    teknoo.east.website.bundle.third_party_authenticated_user_provider.class: 'Teknoo\East\WebsiteBundle\Provider\ThirdPartyAuthenticatedUserProvider'
    teknoo.east.website.bundle.password_authenticated_user_provider.default_algo: 'sodium'

    #Authenticator
    teknoo.east.website.bundle.security.authenticator.oauth2.class: 'Teknoo\East\WebsiteBundle\Security\Authenticator\OAuth2Authenticator'

    #Writer
    teknoo.east.website.bundle.writer.user.class: 'Teknoo\East\WebsiteBundle\Writer\SymfonyUserWriter'

    #Steps
    teknoo.east.website.bundle.allowed_forms: []

    #Bowls
    teknoo.east.website.endpoint.content.bowl.class: 'Teknoo\Recipe\Bowl\FiberRecipeBowl'
    teknoo.east.website.endpoint.media.bowl.class: 'Teknoo\Recipe\Bowl\FiberRecipeBowl'
    teknoo.east.website.endpoint.media.static.class: 'Teknoo\Recipe\Bowl\FiberRecipeBowl'

    teknoo.east.website.endpoint.crud.delete.bowl.class: 'Teknoo\Recipe\Bowl\RecipeBowl'
    teknoo.east.website.endpoint.crud.edit.bowl.class: 'Teknoo\Recipe\Bowl\RecipeBowl'
    teknoo.east.website.endpoint.crud.list.bowl.class: 'Teknoo\Recipe\Bowl\RecipeBowl'
    teknoo.east.website.endpoint.crud.new.bowl.class: 'Teknoo\Recipe\Bowl\RecipeBowl'

services:
    #Front endpoints
    teknoo.east.website.endpoint.content.bowl:
        class: '%teknoo.east.website.endpoint.content.bowl.class%'
        arguments:
            - '@Teknoo\East\Website\Contracts\Recipe\Cookbook\RenderDynamicContentEndPointInterface'
            - 0

    teknoo.east.website.endpoint.content:
        class: 'Teknoo\East\Foundation\EndPoint\RecipeEndPoint'
        public: true
        arguments:
            - '@teknoo.east.website.endpoint.content.bowl'
            - '@service_container'

    teknoo.east.website.endpoint.media.bowl:
        class: '%teknoo.east.website.endpoint.media.bowl.class%'
        arguments:
            - '@Teknoo\East\Website\Contracts\Recipe\Cookbook\RenderMediaEndPointInterface'
            - 0

    teknoo.east.website.endpoint.media:
        class: 'Teknoo\East\Foundation\EndPoint\RecipeEndPoint'
        public: true
        arguments:
            - '@teknoo.east.website.endpoint.media.bowl'
            - '@service_container'

    teknoo.east.website.endpoint.static.bowl:
        class: '%teknoo.east.website.endpoint.media.static.class%'
        arguments:
            - '@Teknoo\East\Website\Contracts\Recipe\Cookbook\RenderStaticContentEndPointInterface'
            - 0

    teknoo.east.website.endpoint.static:
        class: 'Teknoo\East\Foundation\EndPoint\RecipeEndPoint'
        public: true
        arguments:
            - '@teknoo.east.website.endpoint.static.bowl'
            - '@service_container'

    #CRUD endpoints
    teknoo.east.website.endpoint.crud.delete.bowl:
        class: '%teknoo.east.website.endpoint.crud.delete.bowl.class%'
        arguments:
            - '@Teknoo\East\Website\Contracts\Recipe\Cookbook\DeleteContentEndPointInterface'
            - 0

    teknoo.east.website.endpoint.crud.delete:
        class: 'Teknoo\East\Foundation\EndPoint\RecipeEndPoint'
        public: true
        arguments:
            - '@teknoo.east.website.endpoint.crud.delete.bowl'
            - '@service_container'

    teknoo.east.website.endpoint.crud.edit.bowl:
        class: '%teknoo.east.website.endpoint.crud.edit.bowl.class%'
        arguments:
            - '@Teknoo\East\Website\Contracts\Recipe\Cookbook\EditContentEndPointInterface'
            - 0

    teknoo.east.website.endpoint.crud.edit:
        class: 'Teknoo\East\Foundation\EndPoint\RecipeEndPoint'
        public: true
        arguments:
            - '@teknoo.east.website.endpoint.crud.edit.bowl'
            - '@service_container'

    teknoo.east.website.endpoint.crud.list.bowl:
        class: '%teknoo.east.website.endpoint.crud.list.bowl.class%'
        arguments:
            - '@Teknoo\East\Website\Contracts\Recipe\Cookbook\ListContentEndPointInterface'
            - 0

    teknoo.east.website.endpoint.crud.list:
        class: 'Teknoo\East\Foundation\EndPoint\RecipeEndPoint'
        public: true
        arguments:
            - '@teknoo.east.website.endpoint.crud.list.bowl'
            - '@service_container'
            - { criteria: [] }

    teknoo.east.website.endpoint.crud.new.bowl:
        class: '%teknoo.east.website.endpoint.crud.new.bowl.class%'
        arguments:
            - '@Teknoo\East\Website\Contracts\Recipe\Cookbook\CreateContentEndPointInterface'
            - 0

    teknoo.east.website.endpoint.crud.new:
        class: 'Teknoo\East\Foundation\EndPoint\RecipeEndPoint'
        public: true
        arguments:
            - '@teknoo.east.website.endpoint.crud.new.bowl'
            - '@service_container'

    #Steps
    Teknoo\East\WebsiteBundle\Recipe\Step\SearchFormLoader:
        class: 'Teknoo\East\WebsiteBundle\Recipe\Step\SearchFormLoader'
        arguments:
            - '@form.factory'
            - '%teknoo.east.website.bundle.allowed_forms%'
        public: true

    Teknoo\East\WebsiteBundle\Recipe\Step\FormHandling:
        class: 'Teknoo\East\WebsiteBundle\Recipe\Step\FormHandling'
        arguments:
            - '@Teknoo\East\Website\Service\DatesService'
            - '@form.factory'
        public: true

    Teknoo\East\WebsiteBundle\Recipe\Step\RedirectClient:
        class: 'Teknoo\East\WebsiteBundle\Recipe\Step\RedirectClient'
        arguments:
            - '@Psr\Http\Message\ResponseFactoryInterface'
            - '@router'
        public: true

    #Provider
    Teknoo\East\WebsiteBundle\Provider\PasswordAuthenticatedUserProvider:
        class: '%teknoo.east.website.bundle.password_authenticated_user_provider.class%'
        arguments:
            - '@Teknoo\East\Website\Loader\UserLoader'
            - '@Teknoo\East\WebsiteBundle\Writer\SymfonyUserWriter'

    Teknoo\East\WebsiteBundle\Provider\ThirdPartyAuthenticatedUserProvider:
        class: '%teknoo.east.website.bundle.third_party_authenticated_user_provider.class%'
        arguments:
            - '@Teknoo\East\Website\Loader\UserLoader'

    #Command
    Teknoo\East\WebsiteBundle\Command\CreateUserCommand:
        class: '%teknoo.east.website.bundle.command.create_user.class%'
        arguments:
            - '@Teknoo\East\Website\Writer\UserWriter'
            - '@security.user_password_hasher'
        tags:
            - { name: console.command }
        public: false

    #Authenticator
    Teknoo\East\WebsiteBundle\Contracts\Security\Authenticator\UserConverterInterface:
        public: true
        synthetic: true

    Teknoo\East\WebsiteBundle\Security\Authenticator\OAuth2Authenticator:
        class: '%teknoo.east.website.bundle.security.authenticator.oauth2.class%'
        arguments:
            - '@KnpU\OAuth2ClientBundle\Client\ClientRegistry'
            - '@Teknoo\East\Website\Loader\UserLoader'
            - '@Teknoo\East\WebsiteBundle\Writer\SymfonyUserWriter'
            - '@Teknoo\East\WebsiteBundle\Contracts\Security\Authenticator\UserConverterInterface'

    #Writer
    Teknoo\East\WebsiteBundle\Writer\SymfonyUserWriter:
        class: '%teknoo.east.website.bundle.writer.user.class%'
        arguments:
            - '@Teknoo\East\Website\Writer\UserWriter'
            - '@security.user_password_hasher'
        public: true
