parameters:
    #Admin form types
    teknoo.east.website.form_type.doctrine.class: 'Doctrine\Bundle\MongoDBBundle\Form\Type\DocumentType'

    #Command
    teknoo.east.website.bundle.command.create_user.class: 'Teknoo\East\WebsiteBundle\Command\CreateUserCommand'

    #Provider
    teknoo.east.website.bundle.password_authenticated_user_provider.class: 'Teknoo\East\WebsiteBundle\Provider\PasswordAuthenticatedUserProvider'
    teknoo.east.website.bundle.third_party_authenticated_user_provider.class: 'Teknoo\East\WebsiteBundle\Provider\ThirdPartyAuthenticatedUserProvider'
    teknoo.east.website.bundle.password_authenticated_user_provider.default_algo: 'sodium'

    #Authenticator
    teknoo.east.website.bundle.security.authenticator.oauth2.class: 'Teknoo\East\WebsiteBundle\Security\Authenticator\OAuth2Authenticator'

    #Writer
    teknoo.east.website.bundle.writer.user.class: 'Teknoo\East\WebsiteBundle\Writer\SymfonyUserWriter'

    #Steps
    teknoo.east.website.bundle.allowed_forms: []

services:
    #Front endpoints
    teknoo.east.website.endpoint.content:
        class: 'Teknoo\East\Foundation\EndPoint\RecipeEndPoint'
        public: true
        arguments:
            - '@Teknoo\East\Website\Contracts\Recipe\Cookbook\RenderDynamicContentEndPointInterface'
            - '@service_container'

    teknoo.east.website.endpoint.media:
        class: 'Teknoo\East\Foundation\EndPoint\RecipeEndPoint'
        public: true
        arguments:
            - '@Teknoo\East\Website\Contracts\Recipe\Cookbook\RenderMediaEndPointInterface'
            - '@service_container'

    teknoo.east.website.endpoint.static:
        class: 'Teknoo\East\Foundation\EndPoint\RecipeEndPoint'
        public: true
        arguments:
            - '@Teknoo\East\Website\Contracts\Recipe\Cookbook\RenderStaticContentEndPointInterface'
            - '@service_container'

    #CRUD endpoints
    teknoo.east.website.endpoint.crud.delete:
        class: 'Teknoo\East\Foundation\EndPoint\RecipeEndPoint'
        public: true
        arguments:
            - '@Teknoo\East\Website\Contracts\Recipe\Cookbook\DeleteContentEndPointInterface'
            - '@service_container'

    teknoo.east.website.endpoint.crud.edit:
        class: 'Teknoo\East\Foundation\EndPoint\RecipeEndPoint'
        public: true
        arguments:
            - '@Teknoo\East\Website\Contracts\Recipe\Cookbook\EditContentEndPointInterface'
            - '@service_container'

    teknoo.east.website.endpoint.crud.list:
        class: 'Teknoo\East\Foundation\EndPoint\RecipeEndPoint'
        public: true
        arguments:
            - '@Teknoo\East\Website\Contracts\Recipe\Cookbook\ListContentEndPointInterface'
            - '@service_container'
            - { criteria: [] }

    teknoo.east.website.endpoint.crud.new:
        class: 'Teknoo\East\Foundation\EndPoint\RecipeEndPoint'
        public: true
        arguments:
            - '@Teknoo\East\Website\Contracts\Recipe\Cookbook\CreateContentEndPointInterface'
            - '@service_container'

    #Steps
    Teknoo\East\WebsiteBundle\Recipe\Step\SearchFormLoader:
        class: 'Teknoo\East\WebsiteBundle\Recipe\Step\SearchFormLoader'
        arguments:
            - '@form.factory'
            - '%teknoo.east.website.bundle.allowed_forms%'
        public: true

    Teknoo\East\WebsiteBundle\Recipe\Step\FormHandling:
        class: 'Teknoo\East\WebsiteBundle\Recipe\Step\FormHandling'
        arguments:
            - '@Teknoo\East\Website\Service\DatesService'
            - '@form.factory'
        public: true

    Teknoo\East\WebsiteBundle\Recipe\Step\RedirectClient:
        class: 'Teknoo\East\WebsiteBundle\Recipe\Step\RedirectClient'
        arguments:
            - '@Psr\Http\Message\ResponseFactoryInterface'
            - '@router'
        public: true

    #Provider
    Teknoo\East\WebsiteBundle\Provider\PasswordAuthenticatedUserProvider:
        class: '%teknoo.east.website.bundle.password_authenticated_user_provider.class%'
        arguments:
            - '@Teknoo\East\Website\Loader\UserLoader'
            - '@Teknoo\East\WebsiteBundle\Writer\SymfonyUserWriter'

    Teknoo\East\WebsiteBundle\Provider\ThirdPartyAuthenticatedUserProvider:
        class: '%teknoo.east.website.bundle.third_party_authenticated_user_provider.class%'
        arguments:
            - '@Teknoo\East\Website\Loader\UserLoader'

    #Command
    Teknoo\East\WebsiteBundle\Command\CreateUserCommand:
        class: '%teknoo.east.website.bundle.command.create_user.class%'
        arguments:
            - '@Teknoo\East\Website\Writer\UserWriter'
            - '@security.user_password_hasher'
        tags:
            - { name: console.command }
        public: false

    #Authenticator
    Teknoo\East\WebsiteBundle\Contracts\Security\Authenticator\UserConverterInterface:
        public: true
        synthetic: true

    Teknoo\East\WebsiteBundle\Security\Authenticator\OAuth2Authenticator:
        class: '%teknoo.east.website.bundle.security.authenticator.oauth2.class%'
        arguments:
            - '@KnpU\OAuth2ClientBundle\Client\ClientRegistry'
            - '@Teknoo\East\Website\Loader\UserLoader'
            - '@Teknoo\East\WebsiteBundle\Writer\SymfonyUserWriter'
            - '@Teknoo\East\WebsiteBundle\Contracts\Security\Authenticator\UserConverterInterface'

    #Writer
    Teknoo\East\WebsiteBundle\Writer\SymfonyUserWriter:
        class: '%teknoo.east.website.bundle.writer.user.class%'
        arguments:
            - '@Teknoo\East\Website\Writer\UserWriter'
            - '@security.user_password_hasher'
        public: true
