parameters:
  #Front endpoints
  teknoo.east.website.endpoint.content.class: 'Teknoo\East\WebsiteBundle\EndPoint\ContentEndPoint'
  teknoo.east.website.endpoint.media.class: 'Teknoo\East\Website\Doctrine\EndPoint\ODM\MediaEndPoint'
  teknoo.east.website.endpoint.static.class: 'Teknoo\East\WebsiteBundle\EndPoint\StaticEndPoint'

  #Admin endpoints
  teknoo.east.website.endpoint.admin.delete.class: 'Teknoo\East\WebsiteBundle\AdminEndPoint\AdminDeleteEndPoint'
  teknoo.east.website.endpoint.admin.edit.class: 'Teknoo\East\WebsiteBundle\AdminEndPoint\AdminEditEndPoint'
  teknoo.east.website.endpoint.admin.list.class: 'Teknoo\East\WebsiteBundle\AdminEndPoint\AdminListEndPoint'
  teknoo.east.website.endpoint.admin.new.class: 'Teknoo\East\WebsiteBundle\AdminEndPoint\AdminNewEndPoint'

  #Admin form types
  teknoo.east.website.form_type.item.class: 'Teknoo\East\Website\Doctrine\Form\Type\ItemType'
  teknoo.east.website.form_type.content.class: 'Teknoo\East\Website\Doctrine\Form\Type\ContentType'
  teknoo.east.website.form_type.media.class: 'Teknoo\East\WebsiteBundle\Form\Type\MediaType'
  teknoo.east.website.form_type.type.class: 'Teknoo\East\WebsiteBundle\Form\Type\TypeType'
  teknoo.east.website.form_type.user.class: 'Teknoo\East\WebsiteBundle\Form\Type\UserType'
  teknoo.east.website.form_type.doctrine.class: 'Doctrine\Bundle\MongoDBBundle\Form\Type\DocumentType'

  #Class
  teknoo.east.website.item.class: 'Teknoo\East\Website\Doctrine\Object\Item'
  teknoo.east.website.content.class: 'Teknoo\East\Website\Doctrine\Object\Content'
  teknoo.east.website.media.class: 'Teknoo\East\Website\Doctrine\Object\Media'
  teknoo.east.website.type.class: 'Teknoo\East\Website\Object\Type'
  teknoo.east.website.user.class: 'Teknoo\East\Website\Object\User'

  #Path
  teknoo.east.website.view.404-error.file: "@@TeknooEastWebsite/Error/404.html.twig"

  #Admin view path
  teknoo.east.website.view.item.new.file: '@@TeknooEastWebsite/AdminItem/new.html.twig'
  teknoo.east.website.view.item.edit.file: '@@TeknooEastWebsite/AdminItem/edit.html.twig'
  teknoo.east.website.view.item.list.file: '@@TeknooEastWebsite/AdminItem/list.html.twig'

  teknoo.east.website.view.content.new.file: '@@TeknooEastWebsite/AdminContent/new.html.twig'
  teknoo.east.website.view.content.edit.file: '@@TeknooEastWebsite/AdminContent/edit.html.twig'
  teknoo.east.website.view.content.list.file: '@@TeknooEastWebsite/AdminContent/list.html.twig'

  teknoo.east.website.view.media.new.file: '@@TeknooEastWebsite/AdminMedia/new.html.twig'
  teknoo.east.website.view.media.list.file: '@@TeknooEastWebsite/AdminMedia/list.html.twig'

  teknoo.east.website.view.type.new.file: '@@TeknooEastWebsite/AdminType/new.html.twig'
  teknoo.east.website.view.type.edit.file: '@@TeknooEastWebsite/AdminType/edit.html.twig'
  teknoo.east.website.view.type.list.file: '@@TeknooEastWebsite/AdminType/list.html.twig'

  teknoo.east.website.view.user.new.file: '@@TeknooEastWebsite/AdminUser/new.html.twig'
  teknoo.east.website.view.user.edit.file: '@@TeknooEastWebsite/AdminUser/edit.html.twig'
  teknoo.east.website.view.user.list.file: '@@TeknooEastWebsite/AdminUser/list.html.twig'

  #Provider
  teknoo.east.website.bundle.user_provider.class: 'Teknoo\East\WebsiteBundle\Provider\UserProvider'

  #Command
  teknoo.east.website.bundle.command.create_user.class: 'Teknoo\East\WebsiteBundle\Command\CreateUserCommand'

  #Writer
  teknoo.east.website.bundle.writer.user.class: 'Teknoo\East\WebsiteBundle\Writer\UserWriter'

services:
  Teknoo\East\Website\Loader\ContentLoader:
    synthetic: true

  Teknoo\East\Website\Writer\ContentWriter:
    synthetic: true

  teknoo.east.website.deleting.content:
    synthetic: true

  Teknoo\East\Website\Loader\MediaLoader:
    synthetic: true

  Teknoo\East\Website\Writer\MediaWriter:
    synthetic: true

  teknoo.east.website.deleting.media:
    synthetic: true

  Teknoo\East\Website\Loader\ItemLoader:
    synthetic: true

  Teknoo\East\Website\Writer\ItemWriter:
    synthetic: true

  teknoo.east.website.deleting.item:
    synthetic: true

  Teknoo\East\Website\Loader\TypeLoader:
    synthetic: true

  Teknoo\East\Website\Writer\TypeWriter:
    synthetic: true

  teknoo.east.website.deleting.type:
    synthetic: true

  Teknoo\East\Website\Loader\UserLoader:
    synthetic: true

  Teknoo\East\Website\Writer\UserWriter:
    synthetic: true

  teknoo.east.website.deleting.user:
    synthetic: true

  Teknoo\East\Website\Service\DatesService:
    synthetic: true

  Teknoo\East\Website\Service\FindSlugService:
    synthetic: true

  #Front endpoints
  teknoo.east.website.endpoint.content:
    alias: 'Teknoo\East\WebsiteBundle\EndPoint\ContentEndPoint'

  Teknoo\East\WebsiteBundle\EndPoint\ContentEndPoint:
    class: '%teknoo.east.website.endpoint.content.class%'
    arguments:
      - '@Teknoo\East\Website\Loader\ContentLoader'
      - '%teknoo.east.website.view.404-error.file%'
    calls:
      - ['setResponseFactory', ['@Psr\Http\Message\ResponseFactoryInterface']]
      - ['setStreamFactory', ['@Psr\Http\Message\StreamFactoryInterface']]
    tags:
      - { name: "east.endpoint.template" }
    public: true

  teknoo.east.website.endpoint.media.stream.factory:
    alias: 'Psr\Http\Message\StreamFactoryInterface'

  teknoo.east.website.endpoint.media:
    alias: 'Teknoo\East\Website\Doctrine\EndPoint\ODM\MediaEndPoint'

  Teknoo\East\Website\Doctrine\EndPoint\ODM\MediaEndPoint:
    class: '%teknoo.east.website.endpoint.media.class%'
    arguments:
      - '@Teknoo\East\Website\Loader\MediaLoader'
      - '@teknoo.east.website.endpoint.media.stream.factory'
    calls:
      - ['setResponseFactory', ['@Psr\Http\Message\ResponseFactoryInterface']]
      - ['registerRepository', ['@doctrine_mongodb.odm.default_document_manager']]
    public: true

  teknoo.east.website.endpoint.static:
    alias: 'Teknoo\East\WebsiteBundle\EndPoint\StaticEndPoint'

  Teknoo\East\WebsiteBundle\EndPoint\StaticEndPoint:
    class: '%teknoo.east.website.endpoint.static.class%'
    calls:
      - ['setResponseFactory', ['@Psr\Http\Message\ResponseFactoryInterface']]
      - ['setStreamFactory', ['@Psr\Http\Message\StreamFactoryInterface']]
    tags:
      - { name: "east.endpoint.template" }
    public: true

  #Admin endpoints
  teknoo.east.website.endpoint.admin.delete.abstract:
    class: '%teknoo.east.website.endpoint.admin.delete.class%'
    calls:
      - ['setResponseFactory', ['@Psr\Http\Message\ResponseFactoryInterface']]
      - ['setRouter', ['@router']]
    public: true

  teknoo.east.website.endpoint.admin.edit.abstract:
    class: '%teknoo.east.website.endpoint.admin.edit.class%'
    calls:
      - ['setFormFactory', ['@form.factory']]
      - ['setResponseFactory', ['@Psr\Http\Message\ResponseFactoryInterface']]
      - ['setStreamFactory', ['@Psr\Http\Message\StreamFactoryInterface']]
      - ['setDatesService', ['@Teknoo\East\Website\Service\DatesService']]
      - ['setFindSlugService', ['@Teknoo\East\Website\Service\FindSlugService', 'slug']]
    tags:
      - { name: "east.endpoint.template" }
    public: true

  teknoo.east.website.endpoint.admin.list.abstract:
    class: '%teknoo.east.website.endpoint.admin.list.class%'
    calls:
      - ['setResponseFactory', ['@Psr\Http\Message\ResponseFactoryInterface']]
      - ['setStreamFactory', ['@Psr\Http\Message\StreamFactoryInterface']]
    tags:
      - { name: "east.endpoint.template" }
    public: true

  teknoo.east.website.endpoint.admin.new.abstract:
    class: '%teknoo.east.website.endpoint.admin.new.class%'
    calls:
      - ['setFormFactory', ['@form.factory']]
      - ['setResponseFactory', ['@Psr\Http\Message\ResponseFactoryInterface']]
      - ['setStreamFactory', ['@Psr\Http\Message\StreamFactoryInterface']]
      - ['setRouter', ['@router']]
      - ['setFindSlugService', ['@Teknoo\East\Website\Service\FindSlugService', 'slug']]
    tags:
      - { name: "east.endpoint.template" }
    public: true

  #Items
  teknoo.east.website.endpoint.admin.delete.item:
    parent: 'teknoo.east.website.endpoint.admin.delete.abstract'
    calls:
      - ['setDeletingService', ['@teknoo.east.website.deleting.item']]
      - ['setLoader', ['@Teknoo\East\Website\Loader\ItemLoader']]
    public: true

  teknoo.east.website.endpoint.admin.edit.item:
    parent: 'teknoo.east.website.endpoint.admin.edit.abstract'
    calls:
      - ['setLoader', ['@Teknoo\East\Website\Loader\ItemLoader']]
      - ['setWriter', ['@Teknoo\East\Website\Writer\ItemWriter']]
      - ['setFormClass', ['%teknoo.east.website.form_type.item.class%']]
      - ['setViewPath', ['%teknoo.east.website.view.item.edit.file%']]
      - ['setFormOptions', [{ "doctrine_type": "%teknoo.east.website.form_type.doctrine.class%"}]]
    public: true

  teknoo.east.website.endpoint.admin.list.item:
    parent: 'teknoo.east.website.endpoint.admin.list.abstract'
    calls:
      - ['setLoader', ['@Teknoo\East\Website\Loader\ItemLoader']]
      - ['setViewPath', ['%teknoo.east.website.view.item.list.file%']]
    public: true

  teknoo.east.website.endpoint.admin.new.item:
    parent: 'teknoo.east.website.endpoint.admin.new.abstract'
    calls:
      - ['setLoader', ['@Teknoo\East\Website\Loader\ItemLoader']]
      - ['setWriter', ['@Teknoo\East\Website\Writer\ItemWriter']]
      - ['setFormClass', ['%teknoo.east.website.form_type.item.class%']]
      - ['setViewPath', ['%teknoo.east.website.view.item.new.file%']]
      - ['setObjectClass', ['%teknoo.east.website.item.class%']]
      - ['setFormOptions', [{ "doctrine_type": "%teknoo.east.website.form_type.doctrine.class%"}]]
    public: true

  #Contents
  teknoo.east.website.endpoint.admin.delete.content:
    parent: 'teknoo.east.website.endpoint.admin.delete.abstract'
    calls:
      - ['setDeletingService', ['@teknoo.east.website.deleting.content']]
      - ['setLoader', ['@Teknoo\East\Website\Loader\ContentLoader']]
    public: true

  teknoo.east.website.endpoint.admin.edit.content:
    parent: 'teknoo.east.website.endpoint.admin.edit.abstract'
    calls:
      - ['setLoader', ['@Teknoo\East\Website\Loader\ContentLoader']]
      - ['setWriter', ['@Teknoo\East\Website\Writer\ContentWriter']]
      - ['setFormClass', ['%teknoo.east.website.form_type.content.class%']]
      - ['setViewPath', ['%teknoo.east.website.view.content.edit.file%']]
      - ['setFormOptions', [{ "doctrine_type": "%teknoo.east.website.form_type.doctrine.class%"}]]
    public: true

  teknoo.east.website.endpoint.admin.list.content:
    parent: 'teknoo.east.website.endpoint.admin.list.abstract'
    calls:
      - ['setLoader', ['@Teknoo\East\Website\Loader\ContentLoader']]
      - ['setViewPath', ['%teknoo.east.website.view.content.list.file%']]
    public: true

  teknoo.east.website.endpoint.admin.new.content:
    parent: 'teknoo.east.website.endpoint.admin.new.abstract'
    calls:
      - ['setLoader', ['@Teknoo\East\Website\Loader\ContentLoader']]
      - ['setWriter', ['@Teknoo\East\Website\Writer\ContentWriter']]
      - ['setFormClass', ['%teknoo.east.website.form_type.content.class%']]
      - ['setViewPath', ['%teknoo.east.website.view.content.new.file%']]
      - ['setObjectClass', ['%teknoo.east.website.content.class%']]
      - ['setFormOptions', [{ "doctrine_type": "%teknoo.east.website.form_type.doctrine.class%"}]]
    public: true

  #Media
  teknoo.east.website.endpoint.admin.delete.media:
    parent: 'teknoo.east.website.endpoint.admin.delete.abstract'
    calls:
      - ['setDeletingService', ['@teknoo.east.website.deleting.media']]
      - ['setLoader', ['@Teknoo\East\Website\Loader\MediaLoader']]
    public: true

  teknoo.east.website.endpoint.admin.list.media:
    parent: 'teknoo.east.website.endpoint.admin.list.abstract'
    calls:
      - ['setLoader', ['@Teknoo\East\Website\Loader\MediaLoader']]
      - ['setViewPath', ['%teknoo.east.website.view.media.list.file%']]
    public: true

  teknoo.east.website.endpoint.admin.new.media:
    parent: 'teknoo.east.website.endpoint.admin.new.abstract'
    calls:
      - ['setLoader', ['@Teknoo\East\Website\Loader\MediaLoader']]
      - ['setWriter', ['@teknoo.east.website.doctrine.writer.media.new']]
      - ['setFormClass', ['%teknoo.east.website.form_type.media.class%']]
      - ['setViewPath', ['%teknoo.east.website.view.media.new.file%']]
      - ['setObjectClass', ['%teknoo.east.website.media.class%']]
    public: true

  #Type
  teknoo.east.website.endpoint.admin.delete.type:
    parent: 'teknoo.east.website.endpoint.admin.delete.abstract'
    calls:
      - ['setDeletingService', ['@teknoo.east.website.deleting.type']]
      - ['setLoader', ['@Teknoo\East\Website\Loader\TypeLoader']]
    public: true

  teknoo.east.website.endpoint.admin.edit.type:
    parent: 'teknoo.east.website.endpoint.admin.edit.abstract'
    calls:
      - ['setLoader', ['@Teknoo\East\Website\Loader\TypeLoader']]
      - ['setWriter', ['@Teknoo\East\Website\Writer\TypeWriter']]
      - ['setFormClass', ['%teknoo.east.website.form_type.type.class%']]
      - ['setViewPath', ['%teknoo.east.website.view.type.edit.file%']]
    public: true

  teknoo.east.website.endpoint.admin.list.type:
    parent: 'teknoo.east.website.endpoint.admin.list.abstract'
    calls:
      - ['setLoader', ['@Teknoo\East\Website\Loader\TypeLoader']]
      - ['setViewPath', ['%teknoo.east.website.view.type.list.file%']]
    public: true

  teknoo.east.website.endpoint.admin.new.type:
    parent: 'teknoo.east.website.endpoint.admin.new.abstract'
    calls:
      - ['setLoader', ['@Teknoo\East\Website\Loader\TypeLoader']]
      - ['setWriter', ['@Teknoo\East\Website\Writer\TypeWriter']]
      - ['setFormClass', ['%teknoo.east.website.form_type.type.class%']]
      - ['setViewPath', ['%teknoo.east.website.view.type.new.file%']]
      - ['setObjectClass', ['%teknoo.east.website.type.class%']]
    public: true

  #User
  teknoo.east.website.endpoint.admin.delete.user:
    parent: 'teknoo.east.website.endpoint.admin.delete.abstract'
    calls:
      - ['setDeletingService', ['@teknoo.east.website.deleting.user']]
      - ['setLoader', ['@Teknoo\East\Website\Loader\UserLoader']]
    public: true

  teknoo.east.website.endpoint.admin.edit.user:
    parent: 'teknoo.east.website.endpoint.admin.edit.abstract'
    calls:
      - ['setLoader', ['@Teknoo\East\Website\Loader\UserLoader']]
      - ['setWriter', ['@teknoo.east.website.bundle.writer.user']]
      - ['setFormClass', ['%teknoo.east.website.form_type.user.class%']]
      - ['setViewPath', ['%teknoo.east.website.view.user.edit.file%']]
    public: true

  teknoo.east.website.endpoint.admin.list.user:
    parent: 'teknoo.east.website.endpoint.admin.list.abstract'
    calls:
      - ['setLoader', ['@Teknoo\East\Website\Loader\UserLoader']]
      - ['setViewPath', ['%teknoo.east.website.view.user.list.file%']]
    public: true

  teknoo.east.website.endpoint.admin.new.user:
    parent: 'teknoo.east.website.endpoint.admin.new.abstract'
    calls:
      - ['setLoader', ['@Teknoo\East\Website\Loader\UserLoader']]
      - ['setWriter', ['@teknoo.east.website.bundle.writer.user']]
      - ['setFormClass', ['%teknoo.east.website.form_type.user.class%']]
      - ['setViewPath', ['%teknoo.east.website.view.user.new.file%']]
      - ['setObjectClass', ['%teknoo.east.website.user.class%']]
    public: true

  #Provider
  teknoo.east.website.bundle.user_provider:
    alias: 'Teknoo\East\WebsiteBundle\Provider\UserProvider'

  Teknoo\East\WebsiteBundle\Provider\UserProvider:
    synthetic: true

  #Command
  teknoo.east.website.bundle.command.create_user:
    alias: 'Teknoo\East\WebsiteBundle\Command\CreateUserCommand'

  Teknoo\East\WebsiteBundle\Command\CreateUserCommand:
    class: '%teknoo.east.website.bundle.command.create_user.class%'
    arguments:
      - '@Teknoo\East\Website\Writer\UserWriter'
      - '@security.encoder_factory'
    tags:
      - { name: console.command }
    public: false

  #Writer
  teknoo.east.website.bundle.writer.user:
    alias: 'Teknoo\East\WebsiteBundle\Writer\UserWriter'

  Teknoo\East\WebsiteBundle\Writer\UserWriter:
    class: '%teknoo.east.website.bundle.writer.user.class%'
    arguments:
      - '@Teknoo\East\Website\Writer\UserWriter'
      - '@security.encoder_factory'
    public: false
