_teknoo_common_user_recovery:
    path: '/user/access/recovery'
    methods: ['GET', 'POST']
    defaults:
        _controller: 'teknoo.east.common.endpoint.user_recovery.prepare'
        algorithm: '@Teknoo\East\Common\User\RecoveryAccess\TimeLimitedToken'
        errorTemplate: '@@TeknooEastCommon/Error/<error>.html.twig'
        formClass: 'Teknoo\East\CommonBundle\Form\Type\EmailFormType'
        formOptions: {}
        formTemplate: '@@TeknooEastCommon/User/recovery_form.html.twig'
        loader: '@Teknoo\East\Common\Loader\UserLoader'
        submittedTemplate: '@@TeknooEastCommon/User/recovery_submitted.html.twig'
        writer: '@Teknoo\East\CommonBundle\Writer\SymfonyUserWriter'
        recoveryNotificationClass: "%teknoo.east.common.bundle.recovery.notification_class%"
